[package]
name = "screep_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
reqwest = { version = "0.11", features = ["blocking"] }
fern = "0.6"
humantime = "2.1.0"
