[package]
name = "rust-snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = { version = "0.9.0" }
rand = "0.7.3"
bevy-inspector-egui = "0.15.0"
bevy_mod_debugdump = "0.6.0"
bevy_rapier2d = { version = "0.19.0", features = [
    "simd-stable",
    "debug-render"
] }
iyes_loopless = "0.9.1"

# rapier2d = { version = "*" , features = [ "simd-stable" ] }
# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[workspace]
resolver = "2"

[source.crates-io]
replace-with = 'tuna'

[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
