#!/bin/bash

index=1 
filename=""
for arg in $*                     
do
    if [ $index -eq 1 ]
    then
        arg=${arg%.*}
    fi
    filename=$filename"_"$arg
    let index+=1
done

f="l"$filename".rs"

file=src/code/$f

if test -f $file; then
    echo "$file exist"
    exit 0
fi


touch $file
content=$'#![allow(dead_code, unused_imports, unused_macros)]
use std::cmp::*;
use std::collections::*;
use std::ops::Bound::*;
#[cfg(feature = "local")]
struct Solution;

macro_rules! hashmap {
    ($( $key: expr => $val: expr ),*) => {{
         let mut map = ::std::collections::HashMap::new();
         $( map.insert($key, $val); )*
         map
    }}
}

#[cfg(feature = "local")]
pub fn main() {
    println!("res:");
}

'

echo "pub mod l$filename;" >>src/code/mod.rs
echo "$content" >$file